### ISSUE TITLE
配置参数不可扩展除ul li 之外的其他dom结构

### ISSUE THREAD

**Issue by wycfcqt** [ximan/swipeSlide#11]
西门大哥您好，我问一下，这个插件只适用于ul>li这样的dom结构吗？配置参数里的ul 和 li指定其他的dom元素插件就会报错。可以配置成任何结构都适用吗，这样插件的使用范围就更广了。

**Comment by ximan** [comment]
可以啊，ul是父dom，li是子dom就可以呀

**Comment by wycfcqt** [comment]
好的，刚开始用，还没研究透，见谅啊。

**Comment by ximan** [comment]
没关系，那我就关掉了

**Comment by wycfcqt** [comment]
好呢，好呢。
