### ISSUE TITLE
Is need css style in this plugin?

### ISSUE THREAD

**Issue by AdvancedCat** [ximan/swipeSlide#13]
Hey,guys,nice slide plugin is it. And I used it in my project. But a question I should ask you. In your README, I didn't read anything about css style when using this plugin. However this plugin works abnormal without style. So whether I should write some style when using this plugin?
PS: I find style tag in the head tag in your example website. Whether you forgot write style description in README?

**Comment by ximan** [comment]
I'm sorry, it's really my fault.
Because slide will evolve into a wide variety of forms, so I did not put the CSS special statement, I wrote a lot of different examples. You can try to see my example of the source code css.
Hope to help you.
