### ISSUE TITLE
手指滑动导致自动滑动失效

### ISSUE THREAD

**Issue by jmingye** [ximan/swipeSlide#14]
对于设定了autoSlide的情形，如果在第一屏手指横屏左滑或者在最后一屏横屏又滑，大概率会导致其后自动滑动功能失效，页面停止自动滑动

**Comment by ximan** [comment]
你好，感谢关注这个项目。
请问你用的什么手机、什么浏览器、测试的哪个demo？

**Comment by jmingye** [comment]
目前在iphone6s的safari上，测试普通demo里slider3，如果在加载后手动左滑动到前一屏，自动滑动就会停止滑动动画，需要再滑动一屏才会恢复

**Comment by yuana1** [comment]
motoxt1085 的uc浏览器，测试普通demo里slider3
循环完一次之后，如果手动滑动到上一次循环的最后的图片，这个时候不会在自动循环了

**Comment by ximan** [comment]
感谢二位的讨论，已经解决这个bug，详见3.4.4版本。
