### ISSUE TITLE
滑动中 AJAX

### ISSUE THREAD

**Issue by wangcongyi** [ximan/swipeSlide#15]
场景是这样的
      有可能数据太多 需要在滑动的时候 AJAX请求新的数据 再append后面的UL中 
   重新把UL里的HTML清楚 在append这个新的数据 再重新调用swipeSlide
 但是新生成的UL滑动到最后的时候 会马上跳转到第一个LI

重新调用swipeSlide  元素就绑定了两次  所以产生了BUG  
如果 数据很多 需要用AJAX去请求新的数据append 怎么玩？

**Comment by ximan** [comment]
估计是**重新调用swipeSlide**惹的祸。
你这种情况也可以处理，插件有两个参数firstCallback、callback。第一屏的数据可以写到firstCallback里，每次滑动加载数据写到callback里。再配合`function(i,sum,me){}（i为索引值，sum为总和，me为自己）`就可以插入指定位置了。
希望可以帮到你

**Comment by wangcongyi** [comment]
项目中 第一屏还是要用PHP写的  o(╯□╰)o
function(i,sun,me){}  这个是什么？？

**Comment by ximan** [comment]
那就只需要用callback了。
`function(i,sum,me){}（i为索引值，sum为总和，me为自己）`是callback方法，首页参数列表有介绍，例子里也有用到，自己console.log试试。

**Comment by wangcongyi** [comment]
插入之后 但是 新的DOM 没有定位  都‘叠’在一起了  所以一开始 我就想重新init下

**Comment by ximan** [comment]
总数固定么？如果总数固定，容器可以一开始就创建，这样初始化就把位置排列好啦

**Comment by wangcongyi** [comment]
不固定 所有 一开始的时候 我就想重新调用swipeSlide  估计插件不太适合
不过 要不要把你另一个插件 dropload  多加一个功能  
除了上下     左右也行    配置参数放开？

**Comment by ximan** [comment]
这里就讨论swipeSlide吧，你这个需求挺有意思的，下次更新加上。
感谢反馈
