### ISSUE TITLE
提个代码的问题

### ISSUE THREAD

**Issue by a-lian123** [ximan/swipeSlide#3]
line:233 
 if(opts.axisX){
                _moveDistance = _moveResultX;
            }else{
                _moveDistance = _moveResultY;
            }

js中有几处类似的代码，为什么这样写呢？不解？

**Comment by ximan** [comment]
印象中是为了兼容Windows Phone才加的_moveResultX和_moveResultY。
为了判断是横着滚动还是竖着滚动。
看来以后代码要写仔细了，太容易遗忘了。

**Comment by ximan** [comment]
_moveX和_moveResultX都是触摸距离，_moveResultX后面会改变，而_moveX不变。
_moveX用作是IE里的判断，如果触摸距离小，不触发超链接等操作。

            $this.on('click',function(){
                return allowSlideClick;
            });

            // 解决IE滑动触发click
            if(Math.abs(_moveX) < 5){
                allowSlideClick = true;
            }
            setTimeout(function(){
                allowSlideClick = true;
            },100);

**Comment by a-lian123** [comment]
非常感谢！
