### ISSUE TITLE
2.0 到3.0 是不是有broken change啊

### ISSUE THREAD

**Issue by ariesjia** [ximan/swipeSlide#7]
之前的方法好像不能用了，能不能有一个转移的方案

**Comment by ximan** [comment]
首先感谢你使用我的这个js。
能否描述具体一点，或者有demo代码给我看看，最好是在线的。

**Comment by ariesjia** [comment]
callback 里面的不会执行了
```coffee
$slide.swipeSlide
                    continuousScroll:true
                    speed : 3000
                    transitionType : "cubic-bezier(0.22, 0.69, 0.72, 0.88)"
                ,(index)->
                    imageIndex = index
                    $dot.children().eq(index)
                        .addClass('dot-active')
                        .siblings().removeClass('dot-active');

```

**Comment by ximan** [comment]
你好，这个确实是我忘记写出来了。之前的callback写法改了。例如：
$(function(){
    $('.full').swipeSlide({
        autoSwipe:false,
        callback:function(i){
            $('.full li').eq(i).addClass('cur').siblings().removeClass('cur');
        }
    });
});

**Comment by ariesjia** [comment]
谢谢你的更新。
如果可以更新到reademe ，或许还能帮助到其他升级的。

**Comment by ximan** [comment]
感谢，更新了一个版本，这次吧readme完善了一遍。
