### ISSUE TITLE
README.md 文件上的一些问题

### ISSUE THREAD

**Issue by ghost** [ximan/swipeSlide#9]
- 第二个DEMO（文字）和第三个DEMO（大图）的二维码反了
- 第四个DEMO好像有点小Bug，点击上面的导航可以跳转到对应页面，但是没有为对应导航加上 Active 样式

**Comment by ximan** [comment]
@BczYxr 非常感谢反馈！
第一个问题已修改，第二个问题是我代码问题，也修改并提交。
